### ISSUE TITLE
[ROS2] Replace r2b3 with ardent

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#107]
We should update the manifest and regenerate the docker files now that Ardent has been released.
We'll also need to update the source docker file and add the new dependencies (https://github.com/osrf/docker_images/compare/testing_ardent_binaries#diff-611c8dba035afebd27cbc82b2b788f49)

**Comment by ruffsl** [comment]
What tags would we like to provide? What arch are supported?
Does a manifest entry like so look good, similar to the previous r2b3, or perhaps something else?

``` yaml
release_names:
    ardent:
        eol:
        os_names:
            ubuntu:
                os_code_names:
                    xenial:
                        <<: *DEFAULT
                        archs:
                            - amd64
                            - arm32v7
                            - arm64v8
                        tag_names:
                            ros2-core:
                                aliases:
                                    - "$release_name-core"
                                    - "$release_name"
                                    - latest
                            ros2-ros1-bridge:
                                aliases:
                                    - "$release_name-ros1-bridge"
```
