### ISSUE TITLE
After rebuild of the ros:kinetic-ros-core docker image (20.8.2020), tf topic subscriptions do not receive any data

### ISSUE THREAD

**Issue by theduynguyen** [osrf/docker_images#452]
Hi all,

I experienced a strange problem while using the kinetic ROS base images. 
I built an image based on `ros:kinetic-ros-core` and installed ros-kinetic-tf and ros-kinetic-tf2 via apt-get. Then, I created a ROS node to publish transformations into the /tf topic and a node, which subscribes on that topic. The subscriber does not receive any messages.  However, using the `ros:kinetic-robot` image, which has these packages already installed, works. To reproduce my tests, I have uploaded some code  (see [repo (https://github.com/theduynguyen/ros_docker_tf_problem)).

I think it is a ROS+Docker problem, since I tried subscribing from a host system without docker (the container only publishes the /tf) and it worked. On top of all this: my original setup with the `ros:kinetic-ros-core` base image used to work flawlessly before a new version has been released on dockerhub (20.8.2020). Apparently, this problem is also reproducible with the melodic base images. 
I would like to investigate where this problem comes from. I suspect that the ros-kinetic-tf and ros-kinetic-tf2 ubuntu packages recently made changes, which lead to this problem with ROS on docker. Maybe somebody has an idea how to approach this problem.

Thank you very much for your help!

**Comment by ruffsl** [comment]
Could you introspect the ros master and pub/sub node events? E.g. are both nodes registered for the same topic within roscore? Do the slave APIs within the nodes receive the call back from roscore about the updated publisher list of subscribed topics? Are the topics encountering mismatched message types/hash's between publisher and subscriber? I don't suspect API would have been broken within the same distro release.

**Comment by tfoote** [comment]
Your reproduction has a lot of moving parts. 

I tested publishing and subscribing tf inside the new docker images and can't reproduce.

```
ros                 kinetic-robot       0e266071a92b        2 weeks ago         1.19GB
ros                 kinetic             33ffc784e485        2 weeks ago         1.12GB
ros                 kinetic-ros-core    4c4db465725f        2 weeks ago         797MB
```

This much simpler version works. It's using the `/tf_static` topic but I also ran one interactively and tested your [python script](https://github.com/theduynguyen/ros_docker_tf_problem/blob/18ff3e3288411f329fbd8ee16a1d7b9fac960937/tf_problem/ros_nodes/tf_broadcaster.py#L1) and it published successfully as well.
```
docker run -it --rm --net=host ros:kinetic-ros-core roscore
docker run -it --rm --net=host ros:kinetic-ros-core 'bash -c "apt-get update && apt-get install -y ros-kinetic-tf && rosrun tf static_transform_publisher 1 2 3 4 5 6 asdf fdsa 1000"'
docker run -it --rm --net=host ros:kinetic-ros-core 'bash -c "apt-get update && apt-get install -y ros-kinetic-tf && rosrun tf tf_monitor"'
```

Looking at the images https://hub.docker.com/_/ros?tab=tags&page=1&name=kinetic they were built at the same time 14 days ago. 


![Screenshot from 2020-09-02 15-52-07](https://user-images.githubusercontent.com/447804/92047102-189bbd80-ed39-11ea-96f4-c1af9286dfd2.png)
![Screenshot from 2020-09-02 15-52-29](https://user-images.githubusercontent.com/447804/92047104-1a658100-ed39-11ea-999c-32b8d0c0033a.png)

If this is a pure connectivity issue it's unlikely to be related to anything tf, and there are no new releases of geometry or geometry2 in 2 years. So I there shouldn't be any changes there in the last sync. There was a ros_comm release in the sync since the image was built. But to help much more than @ruffsl 's suggestions for debugging we're going to need a better way to reproduce the problem, preferably with fewer moving parts. A typo one two in the many layers of configurations could cause connectivity issues.

If you are experiencing issues related to a sync you can make sure that you put an `apt-get dist-upgrade` at the top of your Dockerfiles to make sure you're running a consistent set of the latest packages.

**Comment by theduynguyen** [comment]
@ruffsl Yeah I did inspect them and subscriptions were fine as expected. Strangely, you can run `rostopic hz tf` but `rostopic echo tf` did not show anything.

@tfoote Thank you for your help! The `apt-get dist-upgrade` turned out to be a game changer! It solved all the problems.

**Comment by ruffsl** [comment]
If you're using docker exec to interactively run commands on containers you've launched via docker compose, I don't think the Ros Master URI and Ros IP environment variables, environment variables that are not baked into the image itself, are replicated onto the Shell session spawned by exec.

**Comment by pichlermarc** [comment]
Hi, everyone.

I know this issue has been closed, but we're currently facing the same problem when using the `ros:melodic-ros-base` image.

I looked at @tfoote's example, and saw that it was using `tf_monitor`, which is written in C++. In our case, however, we were using python nodes. During troubleshooting, a `rostopic echo /tf` showed that it was not receiving any messages. I upgraded packages one by one and managed to narrow it down to `genpy`, which is at version `0.6.12` in the image from Docker Hub. When updating `genpy` to `0.6.14` the issue is resolved and everything works normally again.

I wrote two docker-compose files that illustrate this:

---

```yaml
version: "3.8"
services:
  core:
    image: ros:melodic-ros-base
    command: roscore
    network_mode: host
  publisher:
    image: ros:melodic-ros-base
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf && echo 'starting publisher' && rosrun tf static_transform_publisher 1 2 3 4 5 6 asdf fdsa 1000"
    network_mode: host
  subscriber:
    image: ros:melodic-ros-base
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf && echo 'starting subscriber' && rostopic echo /tf"
    network_mode: host
```

**Expected behavior:** `rostopic echo /tf` prints the messages sent by `static_transform_publisher`
**Actual behavior:** No messages are printed.

---

The following docker-compose file does the exact same thing, but upgrades `ros-melodic-genpy`

```yaml
version: "3.8"
services:
  core:
    image: ros:melodic-ros-base
    command: roscore
    network_mode: host
  publisher:
    image: ros:melodic-ros-base
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf && echo 'starting publisher' && rosrun tf static_transform_publisher 1 2 3 4 5 6 asdf fdsa 1000"
    network_mode: host
  subscriber:
    image: ros:melodic-ros-base
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf ros-melodic-genpy && echo 'starting subscriber' && rostopic echo /tf"
    network_mode: host
```
**This behaves as expected, and outputs the messages sent by `static_transform_publisher`**

---

As to why exactly this is happening, I do not know, but it seems that upgrading that one package would solve it. :smile:

**Comment by pichlermarc** [comment]
Hi @ruffsl, thank you for your comment!

> Could you record the exact docker image sha and substitute them for the tags within the compose file, and check that you can reproduce the issue, and post the compose file here. That way folks like @tfoote could reproduce the issue even after the image tag is updated.

Of course! Here's the docker-compose files including the digests for each image used:


```yaml
version: "3.8"
services:
  core:
    image: ros@sha256:4ec8a1b26ab9738e6def29919168d64ceaa9db97476949ef4c3598ebd740e842
    command: roscore
    network_mode: host
  publisher:
    image: ros@sha256:4ec8a1b26ab9738e6def29919168d64ceaa9db97476949ef4c3598ebd740e842
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf && echo 'starting publisher' && rosrun tf static_transform_publisher 1 2 3 4 5 6 asdf fdsa 1000"
    network_mode: host
  subscriber:
    image: ros@sha256:4ec8a1b26ab9738e6def29919168d64ceaa9db97476949ef4c3598ebd740e842
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf && echo 'starting subscriber' && rostopic echo /tf"
    network_mode: host
```
**Does not print messages sent by `static_transform_publisher`, `genpy` at `0.6.12`**

---

```yaml
version: "3.8"
services:
  core:
    image: ros@sha256:4ec8a1b26ab9738e6def29919168d64ceaa9db97476949ef4c3598ebd740e842
    command: roscore
    network_mode: host
  publisher:
    image: ros@sha256:4ec8a1b26ab9738e6def29919168d64ceaa9db97476949ef4c3598ebd740e842
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf && echo 'starting publisher' && rosrun tf static_transform_publisher 1 2 3 4 5 6 asdf fdsa 1000"
    network_mode: host
  subscriber:
    image: ros@sha256:4ec8a1b26ab9738e6def29919168d64ceaa9db97476949ef4c3598ebd740e842
    command: bash -c "apt-get update && apt-get install -y ros-melodic-tf ros-melodic-genpy && echo 'starting subscriber' && rostopic echo /tf"
    network_mode: host
```
**Works as intended, prints the messages sent by `static_transform_publisher`, `genpy` upgraded to `0.6.14`**

---

Thanks for your help! 
If there's any more information that I can provide please let me know. I'd be happy to do so. :)
