### ISSUE TITLE
how to make sure nodes start after master?

### ISSUE THREAD

**Issue by waspinator** [osrf/docker_images#47]
I often find that my nodes try to start before master is ready, which breaks the system. How do I make sure that the nodes wait for master to be ready (or continually retry)? Using Docker's depends_on isn't guaranteed to work, since Docker only knows when the container is up, but not when ROS master is up.

```
version: '2'

services:

  robot-core:
    build:
      context: .
      dockerfile: robot_core.dockerfile
    volumes:
      - ../data/logs/robot_core:/root/.ros/

  robot-plan:
    build:
      context: .
      dockerfile: robot_plan.dockerfile
    environment:
      - "ROS_HOSTNAME=robot-plan"
      - "ROS_MASTER_URI=http://robot-core:11311"
    volumes:
      - ../data/logs/robot_plan:/root/.ros/

  resolvable:
    image: mgood/resolvable
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/resolv.conf:/tmp/resolv.conf


```

```
<launch>
  <include file="$(find rosbridge_server)/launch/rosbridge_websocket.launch" >
     <arg name="port" value="9090"/>
  </include>
</launch>
```

```
<launch>
    <node name="robot_plan" pkg="robot_plan" type="plan_server.py" output="screen" respawn="true">
        <rosparam command="load" file="$(find robot_plan)/config/config.yaml" />
    </node>
</launch>
```

```
FROM ros:kinetic

RUN apt-get update \
    && apt-get install ros-kinetic-rosbridge-server --yes

RUN ln -snf /bin/bash /bin/sh
RUN mkdir -p /ros_workspace/src/robot_core
WORKDIR /ros_workspace
COPY ["robot_core", "/ros_workspace/src/robot_core"]
RUN source /opt/ros/kinetic/setup.bash; catkin_make

EXPOSE 9090 11311 33690

CMD source devel/setup.bash; roslaunch robot_core robot_core.launch
```

```

FROM ros:kinetic

RUN ln -snf /bin/bash /bin/sh
RUN mkdir -p /ros_workspace/src/robot_msgs
RUN mkdir -p /ros_workspace/src/robot_plan
WORKDIR /ros_workspace
COPY ["robot_msgs", "/ros_workspace/src/robot_msgs"]
COPY ["robot_plan", "/ros_workspace/src/robot_plan"]
RUN source /opt/ros/kinetic/setup.bash; catkin_make

EXPOSE 9090 11311 33690

CMD source devel/setup.bash; roslaunch robot_plan robot_plan.launch
```

**Comment by ruffsl** [comment]
Hello @waspinator . Docker seems to have strong feelings against [controlling startup order](https://docs.docker.com/compose/startup-order/), but because in ROS1 we need the master running before nodes can talk to each other, we'll need accommodate slightly. The doc page I linked above mentions the use of  [wait-for-it](https://github.com/vishnubob/wait-for-it) or [dockerize](https://github.com/jwilder/dockerize), but I think these are mainly just used in polling a given container's network port until it’s accepting TCP connections. Which you could do by checking the container supposedly with the master via port `11311` [by default](http://wiki.ros.org/ROS/Technical%20Overview#Master).

I think a simpler approch my be to take a look at roslaunch's [launch syntax](http://wiki.ros.org/roslaunch/Commandline%20Tools#Launch_syntax) wiki page, you'll see that you can pass roslaunch a `--wait` that will delay the launch until a roscore is detected. As far as I know, I don't think rosrun has this same functionality. So in your case this might be:

``` yaml
  robot-plan:
    build:
      context: .
      dockerfile: robot_plan.dockerfile
    environment:
      - "ROS_HOSTNAME=robot-plan"
      - "ROS_MASTER_URI=http://robot-core:11311"
    volumes:
      - ../data/logs/robot_plan:/root/.ros/
    command: source devel/setup.bash; roslaunch --wait robot_plan robot_plan.launch
```

Although, I would suggest you to amend the default `/ros_entrypoint.sh` script enharted form the base image to source you envoment setup for you [e.g.](https://github.com/googlecartographer/cartographer_ros/blob/fe936b67b1795c07ad1526927a5cc88bc36c8c87/Dockerfile.kinetic#L70), or overide the `ENTRYPOINT` via the Dockerfile, or `entrypoint:` via the docker-compose.yml file.

P.S. This is a good question, perhaps you'd like to cross post it to [answers.ros.org](http://answers.ros.org/) for visability, so that other my find this.
